











//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template (IUnitOfWork.tt).
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ServiceModel;
using BazaarDemo.BackEnd.Domain.Contracts.EntityRepositories;


namespace BazaarDemo.BackEnd.Domain.Contracts.UnitOfWork.DataBase
{

[ServiceContract]
 public interface IUnitOfWork : IDisposable
  {

    #region Properties


    IProductFamilyRepository ProductFamilyRepository { get; }   

    ICustomerRepository CustomerRepository { get; }   

    IProductRepository ProductRepository { get; }   

    #endregion

    #region Methods

    [OperationContract]
    void Commit();

    #endregion
  }


}

