
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template (EntityRepositories.tt).
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq;
using BazaarDemo.BackEnd.Domain.Entities;
using BazaarDemo.BackEnd.Domain.Contracts.EntityRepositories;
using EverNext.Domain.Contracts.Repositories;
using EverNext.Infrastructure.EntityFramework.DbContext;
using System.CodeDom.Compiler;
using EverNext.Domain.Contracts.Model;


namespace BazaarDemo.BackEnd.Infrastructure.DataBase.Repositories.Entities
{

public partial class ProductFamilyRepository : LinqRepository<BazaarDemo.BackEnd.Domain.Entities.ProductFamily>,IProductFamilyRepository
{
    public ProductFamilyRepository (System.Data.Entity.DbContext context) : base(context)
    {

    }
}

}
