//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BazaarDemo.FrontEnd.ConsoleApp.BazaarService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BazaarService.IBazaarService")]
    public interface IBazaarService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBazaarService/TotalProductsInBazaar", ReplyAction="http://tempuri.org/IBazaarService/TotalProductsInBazaarResponse")]
        int TotalProductsInBazaar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBazaarService/TotalProductsInBazaar", ReplyAction="http://tempuri.org/IBazaarService/TotalProductsInBazaarResponse")]
        System.Threading.Tasks.Task<int> TotalProductsInBazaarAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBazaarServiceChannel : BazaarDemo.FrontEnd.ConsoleApp.BazaarService.IBazaarService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BazaarServiceClient : System.ServiceModel.ClientBase<BazaarDemo.FrontEnd.ConsoleApp.BazaarService.IBazaarService>, BazaarDemo.FrontEnd.ConsoleApp.BazaarService.IBazaarService {
        
        public BazaarServiceClient() {
        }
        
        public BazaarServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BazaarServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BazaarServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BazaarServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int TotalProductsInBazaar() {
            return base.Channel.TotalProductsInBazaar();
        }
        
        public System.Threading.Tasks.Task<int> TotalProductsInBazaarAsync() {
            return base.Channel.TotalProductsInBazaarAsync();
        }
    }
}
