
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq;
using BazaarDemo.BackEnd.Domain.Models;
using BazaarDemo.BackEnd.Domain.Contracts.Specifications;
using EverNext.Domain.Contracts.Repositories;
using System.ServiceModel;
using System.CodeDom.Compiler;
using EverNext.Domain.Contracts.Model;
using BazaarDemo.BackEnd.Domain.Entities;


namespace BazaarDemo.BackEnd.Domain.Contracts.ModelRepositories
{

[ServiceContract]
public partial interface ICustomerModelRepository : IMappableRepository<BazaarDemo.BackEnd.Domain.Entities.Customer,BazaarDemo.BackEnd.Domain.Models.CustomerModel,CustomerSpecification>
{
}

}
