
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template (EntityRepositoryInterfaces.tt).
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq;
using BazaarDemo.BackEnd.Domain.Entities;
using EverNext.Domain.Contracts.Repositories;
using System.ServiceModel;
using System.CodeDom.Compiler;
using EverNext.Domain.Contracts.Model;


namespace BazaarDemo.BackEnd.Domain.Contracts.EntityRepositories
{


[ServiceContract]
public partial interface IProductFamilyRepository : IEntityRepository<BazaarDemo.BackEnd.Domain.Entities.ProductFamily>,IAggregateRoot
{
}

}
