
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Linq.Expressions;

using BazaarDemo.BackEnd.Domain.Entities;
using BazaarDemo.BackEnd.Domain.Contracts.Specifications;
using System.Diagnostics.CodeAnalysis;
using System.CodeDom.Compiler;
using System.Runtime.Serialization;
using EverNext.Domain.Model;
using System.Collections.Generic;


namespace BazaarDemo.BackEnd.Domain.Contracts.Specifications
{

[Serializable]
[DataContract(Name = "ProductFamilySpecification", Namespace = "http://schemas.datacontract.org/2004/07/EverNext.Domain.Model.Specifications")]
[ExcludeFromCodeCoverage]
[GeneratedCode("SpecificationImplementationCodeGen","1.0")]
public partial class ProductFamilySpecification : Specification<BazaarDemo.BackEnd.Domain.Entities.ProductFamily>
{
		[DataMember]
		public bool? Negate
		{
			get;
			set;
		}

		[DataMember]
		public ProductFamilySpecification And
		{
			get;
			set;
		}

		[DataMember]
		public ProductFamilySpecification Or
		{
			get;
			set;
		}

	[DataMember]
	public Nullable<int> ProductFamilyId
	{
		get; 
		set;
	}

	[DataMember]
	public ICollection<Nullable<int>> ProductFamilyIdList
	{
		get;
		set;
	}

	[DataMember]
	public string ProductFamilyName
	{
		get; 
		set;
	}

	[DataMember]
	public ICollection<string> ProductFamilyNameList
	{
		get;
		set;
	}


	[DataMember]
	public string ProductFamilyNameContains
	{
		get;
		set;
	}
	
	[DataMember]
	public string ProductFamilyNameStartsWith
	{
		get;
		set;
	}
	
	[DataMember]
	public string ProductFamilyNameEndsWith
	{
		get;
		set;
	}

	[DataMember]
	public string ProductFamilyDescription
	{
		get; 
		set;
	}

	[DataMember]
	public ICollection<string> ProductFamilyDescriptionList
	{
		get;
		set;
	}


	[DataMember]
	public string ProductFamilyDescriptionContains
	{
		get;
		set;
	}
	
	[DataMember]
	public string ProductFamilyDescriptionStartsWith
	{
		get;
		set;
	}
	
	[DataMember]
	public string ProductFamilyDescriptionEndsWith
	{
		get;
		set;
	}


    #region Navigation Properties
    

	[DataMember]
	public ProductSpecification Products
	{
		get;
		set;
	}

        #endregion

    

	/// <summary>
	/// Default constructor (needed for serialization)
	/// Initializes a new instance of the <see cref="ProductFamilySpecification"/> class.
	/// </summary>
	public ProductFamilySpecification()
	{

	}

	

	/// <summary>
	/// Initializes a new instance of the <see cref="ProductFamilySpecification"/> class.
	/// </summary>
	/// <param name="initializeNavigationProperties">if set to <c>true</c> initialize navigation properties.</param>
	public ProductFamilySpecification(bool initializeNavigationProperties)
	{
		if(!initializeNavigationProperties)
			return;


		this.Products = new ProductSpecification();

	}


    #region ISpecification Members
    

	public override Expression<Func<BazaarDemo.BackEnd.Domain.Entities.ProductFamily, bool>> GetExpression()
	{
		Expression<Func<BazaarDemo.BackEnd.Domain.Entities.ProductFamily, bool>> expression = x => true;


		if(ProductFamilyIdList!=null&&ProductFamilyIdList.Count > 0)
			expression = expression.And(x => ProductFamilyIdList.Contains(x.ProductFamilyId));



		if(ProductFamilyId.HasValue)
			expression = expression.And(x => x.ProductFamilyId == ProductFamilyId.Value);


		if(ProductFamilyNameList!=null&&ProductFamilyNameList.Count > 0)
			expression = expression.And(x => ProductFamilyNameList.Contains(x.ProductFamilyName));

	
		if(!string.IsNullOrWhiteSpace(ProductFamilyName))  
			expression = expression.And(x => x.ProductFamilyName.Equals(ProductFamilyName));
			
		if(!string.IsNullOrWhiteSpace(ProductFamilyNameContains))  
			expression = expression.And(x => x.ProductFamilyName.Contains(ProductFamilyNameContains));
			
		if(!string.IsNullOrWhiteSpace(ProductFamilyNameStartsWith))
			expression = expression.And(x => x.ProductFamilyName.StartsWith(ProductFamilyNameStartsWith));

		if(!string.IsNullOrWhiteSpace(ProductFamilyNameEndsWith))
			expression = expression.And(x => x.ProductFamilyName.EndsWith(ProductFamilyNameEndsWith));


		if(ProductFamilyDescriptionList!=null&&ProductFamilyDescriptionList.Count > 0)
			expression = expression.And(x => ProductFamilyDescriptionList.Contains(x.ProductFamilyDescription));

	
		if(!string.IsNullOrWhiteSpace(ProductFamilyDescription))  
			expression = expression.And(x => x.ProductFamilyDescription.Equals(ProductFamilyDescription));
			
		if(!string.IsNullOrWhiteSpace(ProductFamilyDescriptionContains))  
			expression = expression.And(x => x.ProductFamilyDescription.Contains(ProductFamilyDescriptionContains));
			
		if(!string.IsNullOrWhiteSpace(ProductFamilyDescriptionStartsWith))
			expression = expression.And(x => x.ProductFamilyDescription.StartsWith(ProductFamilyDescriptionStartsWith));

		if(!string.IsNullOrWhiteSpace(ProductFamilyDescriptionEndsWith))
			expression = expression.And(x => x.ProductFamilyDescription.EndsWith(ProductFamilyDescriptionEndsWith));
		
		//
		// Navigation properties
		//


		if(this.Products != null)
		{

			var subExpression = Products.GetExpression();
			expression = expression.And(x => x.Products.AsQueryable().Any(subExpression));

		}
	
		if (Negate != null && Negate.Value)
		{
			expression = Expression.Lambda<Func<BazaarDemo.BackEnd.Domain.Entities.ProductFamily,bool>>(Expression.Not(expression.Body), expression.Parameters);
		}
			
		if(And != null)
		{
			expression = expression.And(And.GetExpression());
		}

		if (Or != null)
		{
			expression = expression.Or(Or.GetExpression());
		}

		return expression;
	}


	public override bool IsSatisfiedBy(BazaarDemo.BackEnd.Domain.Entities.ProductFamily entity)
	{
		// convert single entity to a IQueryable object, 
		// in order to be able to use lambda expressions
		IQueryable<BazaarDemo.BackEnd.Domain.Entities.ProductFamily> entities = (new[] { entity }).AsQueryable();
		
		return entities.Any(this.GetExpression());
	}
	
        #endregion

    
}

}
