












//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template (UnitOfWork.tt).
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Objects;
using System.Data.Objects.DataClasses;

using System.Linq;

using BazaarDemo.BackEnd.Domain.Contracts.UnitOfWork;
using System.Diagnostics.CodeAnalysis;
using System.CodeDom.Compiler;
using System.Runtime.Serialization;
using EverNext.Domain.Model;
using BazaarDemo.BackEnd.Domain.Contracts.EntityRepositories;
using BazaarDemo.BackEnd.Domain.Contracts.UnitOfWork.DataBase;
using BazaarDemo.BackEnd.Infrastructure.DataBase.Context;

namespace BazaarDemo.BackEnd.Infrastructure.DataBase.UnitOfWork
{

[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
[System.CodeDom.Compiler.GeneratedCode("GeneratedCode","1.0")]
 public class UnitOfWork : IUnitOfWork
  {
    System.Data.Entity.DbContext _context;

    public UnitOfWork(): this(new BazaarContext())
    {

    }

    public UnitOfWork(System.Data.Entity.DbContext entities)
    {
        if (entities == null)
        {
            throw new ArgumentNullException("context wasn't supplied");
        }

        _context = entities;
        (_context as IObjectContextAdapter).ObjectContext.Connection.Open();
    }


    #region Properties


    IProductFamilyRepository _ProductFamilyRepository;
    public IProductFamilyRepository ProductFamilyRepository
    {
        get
        {
            return _ProductFamilyRepository;
        }
        set
        {
            _ProductFamilyRepository = value;
        }
    }   

    ICustomerRepository _CustomerRepository;
    public ICustomerRepository CustomerRepository
    {
        get
        {
            return _CustomerRepository;
        }
        set
        {
            _CustomerRepository = value;
        }
    }   

    IProductRepository _ProductRepository;
    public IProductRepository ProductRepository
    {
        get
        {
            return _ProductRepository;
        }
        set
        {
            _ProductRepository = value;
        }
    }   

    #endregion

    #region Methods

    public void Commit()
    {
        _context.SaveChanges();
    }
    
    public void Dispose()
    {
        Dispose(true);
        GC.SuppressFinalize(this);
    }

    protected virtual void Dispose(bool disposing)
    {
        if (disposing)
        {
            if (_context != null)
            {
                _context.Dispose();
                _context = null;
            }
        }
    }

    #endregion
  }


}

